import subprocess


def run(command):
    result = subprocess.run(
        command,
        shell=True,
        capture_output=True,
        text=True
    )
    return result.stdout.strip()


# -------------------------
# Collect evidence
# -------------------------

nginx = run("systemctl is-active nginx")

docker_count = run(
    "docker ps -q | wc -l"
)

ports = run(
    "ss -lnt | awk 'NR>1 {print $4}'"
)

load = run(
    "awk '{print $1}' /proc/loadavg"
)

disk = run(
    "df -P / | awk 'NR==2 {print $5}'"
)


# -------------------------
# Deterministic analysis
# -------------------------

findings = []

if nginx != "active":
    findings.append(
        "NGINX is not running."
    )

if docker_count == "0":
    findings.append(
        "No Docker containers are currently running."
    )

backend_ports = []

for port in ["8000", "8080", "3000", "5000"]:
    if f":{port}" in ports:
        backend_ports.append(port)

if not backend_ports:
    findings.append(
        "No common backend application port is listening."
    )

disk_percent = int(disk.replace("%", ""))

if disk_percent >= 90:
    findings.append(
        f"Disk usage is critically high at {disk_percent}%."
    )

# -------------------------
# Determine incident
# -------------------------

if nginx != "active" and docker_count == "0":
    root_cause = (
        "There is currently no active NGINX service "
        "and no running Docker application on this server. "
        "A 502 cannot currently be generated by an NGINX "
        "instance on this host."
    )

else:
    root_cause = (
        "An active application stack exists. "
        "Additional service and upstream checks are required."
    )


# -------------------------
# Output
# -------------------------

print("\n===== DETERMINISTIC INCIDENT ANALYSIS =====")

print("\nFACTS:")

for finding in findings:
    print("-", finding)

print("\nROOT CAUSE:")
print(root_cause)

print("\nSYSTEM LOAD:")
print(load)

print("\nDISK:")
print(disk)
