name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Backend
        run: |
          docker build \
            -t jashwanth0310/login-backend:latest \
            ./backend

      - name: Build Frontend
        run: |
          docker build \
            -t jashwanth0310/login-frontend:latest \
            ./frontend

      - name: Build NGINX
        run: |
          docker build \
            -t jashwanth0310/login-nginx:latest \
            ./nginx

      - name: Push Backend
        run: |
          docker push jashwanth0310/login-backend:latest

      - name: Push Frontend
        run: |
          docker push jashwanth0310/login-frontend:latest

      - name: Push NGINX
        run: |
          docker push jashwanth0310/login-nginx:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/ai-devops
            docker compose pull
            docker compose up -d
            docker compose ps
